version: "3"
services:
  mysql:
    image: mysql:8.0.27
    container_name: mysql_servertree
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./var/mysql/data:/var/lib/mysql
    command: mysqld --sql_mode=""
