"""Initial Alembic

Revision ID: 2012fa633b7c
Revises:
Create Date: 2021-11-26 01:18:32.607224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2012fa633b7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'connection_type',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'environment',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'operating_system',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('version', sa.String(length=50), nullable=False),
        sa.Column('architect', sa.String(length=6), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'role',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('role', sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('role')
    )
    op.create_table(
        'server',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('environment_id', sa.Integer(), nullable=False),
        sa.Column('operating_system_id', sa.Integer(), nullable=False),
        sa.Column('cpu', sa.String(length=50), nullable=False),
        sa.Column('ram', sa.String(length=50), nullable=False),
        sa.Column('hdd', sa.String(length=50), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
        sa.ForeignKeyConstraint(['operating_system_id'], ['operating_system.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'user',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('firstname', sa.String(length=128), nullable=False),
        sa.Column('lastname', sa.String(length=128), nullable=False),
        sa.Column('email', sa.String(length=256), nullable=False),
        sa.Column('password', sa.String(length=256), nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_table(
        'access',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('server_id', sa.Integer(), nullable=False),
        sa.Column('connection_type_id', sa.Integer(), nullable=False),
        sa.Column('ip_local', sa.String(length=15), nullable=True),
        sa.Column('port_local', sa.String(length=5), nullable=True),
        sa.Column('ip_public', sa.String(length=15), nullable=True),
        sa.Column('port_public', sa.String(length=5), nullable=True),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('password', sa.String(length=50), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['connection_type_id'], ['connection_type.id'], ),
        sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'service',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('server_id', sa.Integer(), nullable=False),
        sa.Column('service', sa.String(length=50), nullable=False),
        sa.Column('version', sa.String(length=50), nullable=False),
        sa.Column('architect', sa.String(length=6), nullable=False),
        sa.Column('ip_local', sa.String(length=15), nullable=True),
        sa.Column('port_local', sa.String(length=5), nullable=True),
        sa.Column('ip_public', sa.String(length=15), nullable=True),
        sa.Column('port_public', sa.String(length=5), nullable=True),
        sa.Column('install_dir', sa.String(length=50), nullable=False),
        sa.Column('log_dir', sa.String(length=50), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service')
    op.drop_table('access')
    op.drop_table('user')
    op.drop_table('server')
    op.drop_table('role')
    op.drop_table('operating_system')
    op.drop_table('environment')
    op.drop_table('connection_type')
    # ### end Alembic commands ###
